server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
baseurl:
  leetcode: 
    request-url: "https://leetcode.com/graphql/"
    referrer-url: "https://leetcode.com/%s/"
  github:  
    request-url: "https://api.github.com/graphql"