server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
baseurl:
  leetcode: 
    request-url: "https://leetcode.com/graphql/"
    referrer-url: "https://leetcode.com/%s/"
  github:  
    request-url: "https://api.github.com/graphql"
  mongodb:
    request-url: "https://data.mongodb-api.com/app/data-okjli/endpoint/data/v1/action"
    find-request: "/find"
    datasource: "SohamsWebPortal"
    database: "Web_Portal_Database"